{% set name = "scikit-allel" %}
{% set version = "1.2.0" %}
{% set sha256 = "484ef37b3fdb03c49c2698db3474c154b4e19f134f1561e850bb214e1600f8f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - setuptools_scm
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - numexpr
    - dask >=0.15
    - h5py
    - bcolz
    - zarr >=2.2
    - numcodecs
    - matplotlib
    - seaborn
    - pandas
    - pomegranate

test:
  requires:
    - pytest
  imports:
    - allel
    - allel.opt.model
    - allel.opt.stats
    - allel.opt.io_vcf_read
  commands:
    - pytest -v --pyargs allel

about:
  home: http://github.com/cggh/scikit-allel
  license: MIT
  license_file: LICENSE
  summary: 'A Python package for exploring and analysing genetic variation data.'
  doc_url: http://scikit-allel.readthedocs.io/
  dev_url: https://github.com/cggh/scikit-allel

extra:
  recipe-maintainers:
    - alimanfoo
    - hardingnj
